Repository boostcampaitech4lv23recsys1/final-project-level3-recsys-02, pull requests merged in 2023-01, with the labels that each got.

#27 fix: Fix crawling.py to handle unexpected Webdriver closure
  crawling/crawling.py
Labels: enhancement

#28 merge: API_crawl v3.0
  API/lastfm_api_crawl.py
Labels: enhancement

#30 merge: API_crawl v4.0
  API/README.md
  API/api_key
  API/etc/artist_api.py
  API/etc/lastfm.ipynb
  API/lastfm_api_crawl.py
  API/lastfm_api_crawl.sh
Labels: bug, enhancement

#32 merge: API_crawl v5.0
  API/lastfm_api_crawl.py
Labels: bug
